### ISSUE TITLE
Trivial unsoundness throughout entire library

### ISSUE THREAD

**Issue by repnop** [frank2/pkbuffer#1]
Hi there, I'm not sure about your level of knowledge with Rust, but this entire library is quite unsound and extremely easy to cause undefined behavior with, for example:
```rust
/// Convert the given reference of type ```T``` to a mutable [`u8`](u8) [slice](slice).
pub fn ref_to_mut_bytes<T>(data: &mut T) -> &mut [u8] {
    let ptr = data as *mut T as *mut u8;
    let size = std::mem::size_of::<T>();

    unsafe { std::slice::from_raw_parts_mut(ptr, size) }
}

fn main() {
    let mut bools = [false; 3];
    let bytes = ref_to_mut_bytes(&mut bools);
    bytes.iter_mut().for_each(|byte| *byte = 3);

    println!("{:?}", bools);
}
```
when run with MIRI:
```
Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.65s
     Running `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri target/miri/x86_64-unknown-linux-gnu/debug/playground`
error: Undefined Behavior: type validation failed: encountered 0x03, but expected a boolean
    --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2165:25
     |
2165 |         Display::fmt(if *self { "true" } else { "false" }, f)
     |                         ^^^^^ type validation failed: encountered 0x03, but expected a boolean
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
             
     = note: inside `<bool as std::fmt::Display>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2165:25
     = note: inside `<bool as std::fmt::Debug>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2158:9
     = note: inside `<&bool as std::fmt::Debug>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2128:62
     = note: inside closure at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/builders.rs:404:17
     = note: inside `std::result::Result::<(), std::fmt::Error>::and_then::<(), [closure@core::fmt::builders::DebugInner::entry::{closure#0}]>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1311:22
     = note: inside `core::fmt::builders::DebugInner::entry` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/builders.rs:390:23
     = note: inside `std::fmt::DebugList::entry` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/builders.rs:609:9
     = note: inside `std::fmt::DebugList::entries::<&bool, std::slice::Iter<bool>>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/builders.rs:643:13
     = note: inside `<[bool] as std::fmt::Debug>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2331:9
     = note: inside `<&[bool] as std::fmt::Debug>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2128:62
     = note: inside `std::array::<impl std::fmt::Debug for [bool; 3]>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/mod.rs:254:9
     = note: inside `std::fmt::write` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:1190:17
     = note: inside `<std::io::StdoutLock as std::io::Write>::write_fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:1657:15
     = note: inside `<&std::io::Stdout as std::io::Write>::write_fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:821:9
     = note: inside `<std::io::Stdout as std::io::Write>::write_fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:795:9
     = note: inside `std::io::stdio::print_to::<std::io::Stdout>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:1163:21
     = note: inside `std::io::_print` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:1176:5
note: inside `main` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:99:9
     --> src/main.rs:14:5
     |
14   |     println!("{:?}", bools);
     |     ^^^^^^^^^^^^^^^^^^^^^^^
     = note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
     [...]

error: aborting due to previous error
```
Among other things such as allowing the reading of uninitialized memory (padding bytes), arbitrary pointer dereferencing, etc. all within safe code -- which kind of goes against the purpose of Rust. So I'd recommend that you either mark everything as `unsafe` and document the validity requirements, or take a safer approach that other crates such as [bytemuck](https://crates.io/crates/bytemuck) involving `unsafe` traits and derive macros to ensure its valid to convert types between byte slices and back.

If you have any questions, want clarification on anything I mentioned, or want further examples, just let me know :+1:

**Comment by frank2** [comment]
Oh! I'm sorry for not noticing this sooner! Thank you for the clarification-- and the new tool to use! I'm still relatively new to Rust and come from a mostly C background, which probably explains why I'm emitting undefined behavior unintentionally. I wasn't aware this caused undefined (and therefore unsafe) behavior!

Where can I get Miri? That seems like a very useful tool to ween me away from the undefined nature of C. I'll definitely work toward making this library more explicitly obvious (or even fix) where undefined behavior might happen. Thank you for reporting this! (edit: I found the rustup command! Thanks again for introducing this to me!)

**Comment by frank2** [comment]
This is the next thing to fix on the docket for this library in my notes, so I'm going to leave this ticket open until I handle this.

**Comment by frank2** [comment]
I've opted to use the bytemuck library to handle the conversion of byteslices to references. Your example shouldn't compile anymore. Check out the diff and let me know what you think. https://github.com/frank2/pkbuffer/commit/6888aba6901ed3ce46aaef58d986021a25d3ba4b

**Comment by repnop** [comment]
> Where can I get Miri? 

Easiest way to test code is generally on https://play.rust-lang.org, under "Tools" you can run code there with MIRI, which is usually a bit more convenient if you don't need local-source :+1: but having it locally as you mentioned you found works too!

> Check out the diff and let me know what you think.

I didn't look very closely, but for a lot of the underlying stuff you can use the methods provided by `bytemuck` for the conversions as well. I assume you want to have a slightly different API than `bytemuck`, but underpinning that with the functions that it provides may help with ensuring things are safely done :smiley: Also you may want to use the derive macros from `bytemuck` for you example struct in the docs, since it'll check the invariants that need upheld for you :+1: 

For more information on low-level Rust stuff, you can check out the [Unsafe Code Guidelines](https://github.com/rust-lang/unsafe-code-guidelines/) repo and browse around (especially the issues) to get a cursory look at what things you need to pay attention to as well as some areas that Rust diverges from C. There's also the [Rustonomicon](https://doc.rust-lang.org/nomicon/intro.html) which has a more thorough introduction to `unsafe` and goes through example projects, which might help

**Comment by frank2** [comment]
Thanks so much for all the info, that's definitely going to help since I've been writing a lot of low-level libraries that require unsafe functionality!

Going to close this now that the underlying unsoundness issues are fixed (and now that I know how to deal with unaligned data properly), thanks again for the bug report!
